[project]
name = "laser-control"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "keyboard>=0.13.5; sys_platform == 'win32'",
    "numpy>=1.24.1",
    "opencv-python>=4.7.0.72",
    "PyQt5>=5.15.9",
    "pywin32>=308; sys_platform == 'win32'",
]

[tool.uv]
environments = ["sys_platform == 'win32'"]
